svftocsv-converter/Models/SvfFileUploadModel.cs
using System.ComponentModel;
using System.Web;

namespace svftocsv_converter.Models {
    public class SvfFileUploadModel {
        [DisplayName("SVF File")]
        public HttpPostedFileBase File { get; set; }

        [DisplayName("Patch Height (mm)")]
        public double PatchHeight { get; set; }

        [DisplayName("Color Bar Name")]
        public string ColorBarName { get; set; }

        public string DefaultColorBarName => "Color Bar Name";

        [DisplayName("Color Bar Description")]
        public string ColorBarDescription { get; set; }

        public string DefaultColorBarDescription => "Description";

        [DisplayName("Email Recipients")]
        public string EmailRecipients { get; set; }

        public SvfFileUploadModel() {
            PatchHeight = 8;
            ColorBarName = DefaultColorBarName;
            ColorBarDescription = DefaultColorBarDescription;
        }
    }
}

svftocsv-converter/Controllers/ConvertSvfToCsvController.cs
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;

using svf.to.csv.azure.mail.Enums;
using svf.to.csv.azure.mail.MailJet;
using svf.to.csv.converter.lib;

using svftocsv_converter.Models;

namespace svftocsv_converter.Controllers {
    public class ConvertSvfToCsvController : Controller {
        public ActionResult Index() {
            var model = new SvfFileUploadModel();
            return View(model);
        }

        //---------------------------------------------------------------------

        [HttpPost]
        public ActionResult Convert(SvfFileUploadModel model) {
            if (!string.IsNullOrWhiteSpace(model.File?.FileName)) {
                string path = AppDomain.CurrentDomain.BaseDirectory + "/App_Data/uploads/";
                string filename = Path.GetFileName(model.File?.FileName);

                string absoluteFilename = Path.Combine(path, filename);
                model.File?.SaveAs(absoluteFilename);

                string csvFilename = convertToCsv(absoluteFilename, model.ColorBarName, model.ColorBarDescription,
                                                  model.PatchHeight, model.EmailRecipients, out var messages);
                TempData["LastUploadFilename"] = Path.GetFileName(csvFilename);
                TempData["LastUploadAbsPath"] = csvFilename;
                TempData["Messages"] = messages;
            }

            return RedirectToAction("Downloads");
        }

        //---------------------------------------------------------------------

        public ActionResult Downloads() {
            var dir = new DirectoryInfo(Server.MapPath("~/App_Data/uploads/"));
            if (!dir.Exists) {
                dir.Create();
            }

            var files = dir.GetFiles("*.*").ToList();
            return View(files);
        }

        //---------------------------------------------------------------------

        public FileResult Download(string fileName) {
            var fileVirtualPath = "~/App_Data/uploads/" + Path.GetFileName(fileName);
            return File(fileVirtualPath, System.Net.Mime.MediaTypeNames.Application.Octet,
                        Path.GetFileName(fileVirtualPath));
        }

        //---------------------------------------------------------------------

        public ActionResult Delete(string fileName) {
            var fileVirtualPath = Path.Combine(Server.MapPath("~/App_Data/uploads/"), fileName);
            System.IO.File.Delete(fileVirtualPath);
            return RedirectToAction("Downloads");
        }

        //---------------------------------------------------------------------

        private static string convertToCsv(string svfFilename, string colorBarName, string colorBarDescr,
                                           double patchHeight, string emailRecipients,
                                           out string messages) {
            messages = "";
            var emailService = new MailJetWrapper();

            // convert to CSV and download
            SvfFileImporter svfFileImporter = new SvfFileImporter();
            DataTable data = null;
            try {
                svfFileImporter.ImportSvf(svfFilename);
            }
            catch (Exception e) {
                if (svfFileImporter.Messages.Length > 0) {
                    messages = $"Import Errors:  {svfFileImporter.Messages}";
                }

                emailService.Send(MessageType.SvfToCsvConversion_Failure, emailRecipients, svfFilename, "",
                                  e.Message);

                return "";
            }


            data = svfFileImporter.Data;
            CsvFileExporter csvFileExporter = new CsvFileExporter();
            var csvDirectory = buildCsvDirectory(svfFilename);
            string csvFilename = "";
            try {
                // TODO - SvfFile must read it's own data / create internal data table
                //        along with other properties...
                csvFilename = csvFileExporter.Export(data, colorBarName, colorBarDescr,
                                                     svfFileImporter.SvfFile.PatchWidth, patchHeight,
                                                     svfFileImporter.SvfFile.PatchesPerZone,
                                                     svfFileImporter.SvfFile.UsedKeys, csvDirectory);
            }
            catch (Exception e) {
                if (csvFileExporter.Messages.Length > 0) {
                    if (messages.Length > 0) messages += $"{Environment.NewLine}{Environment.NewLine}";
                    messages = $"Export Errors:  {csvFileExporter.Messages}";
                }

                emailService.Send(MessageType.SvfToCsvConversion_Failure, emailRecipients, svfFilename, "",
                                  e.Message);
            }

            emailService.Send(MessageType.SvfToCsvConversion_Success, emailRecipients, svfFilename, csvFilename,
                              "");

            return csvFilename;
        }

        private static string buildCsvDirectory(string svfFilename) {
            string directory = Path.GetDirectoryName(svfFilename) ?? @"c:\temp";

            //string filename = Path.GetFileNameWithoutExtension(svfFilename) ?? "temp";
            //var csvFilename = Path.Combine(directory, filename) + ".csv";
            //return csvFilename;
            return directory;
        }
    }
}

svftocsv-converter/Views/ConvertSvfToCsv/Downloads.cshtml
@model List<FileInfo>

@{
    ViewBag.Title = "Downloads";
}

<h2>Downloads</h2>


@if (!string.IsNullOrWhiteSpace(TempData["Messages"] as string)) {
    <p>
        <b>Error Message:</b> @TempData["Messages"]
    </p>
}


@if (!string.IsNullOrWhiteSpace(TempData["LastUploadFilename"] as string)) {
    <p>
        <b>Most recently converted file:</b> @TempData["LastUploadFilename"] @Html.ActionLink("Download", "Download", new {FileName = TempData["LastUploadAbsPath"]})
    </p>
}


<table id="example" class="table table-striped table-bordered">
    <tr>
        <th>File Name</th>
        <th>Created</th>
        <th></th>
        <th></th>
    </tr>

    @* TODO - file size, date processed / stored on server.... i.e. show some of the file properties! *@

    @for (var i = 0; i <= Model.Count - 1; i++) {
        <tr>
            <td>@Path.GetFileName(Model[i].FullName) </td>
            <td>@Model[i].CreationTime</td>
            <td>@Html.ActionLink("Download", "Download", new {FileName = Path.GetFileName(Model[i].FullName)}) </td>
            <td>@Html.ActionLink("Delete", "Delete", new {FileName = Path.GetFileName(Model[i].FullName)}) </td>
        </tr>
    }
</table>

svftocsv-converter/Views/ConvertSvfToCsv/Index.cshtml
@model svftocsv_converter.Models.SvfFileUploadModel

@{
    ViewBag.Title = "Index";
}

<h2>Upload</h2>


@using (Html.BeginForm("Convert", "ConvertSvfToCsv", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.File)
            </div>
        </div><!-- /.col -->

        <div class="col-md-4">
            <div class="form-group">
                <input type="file" name="file" id="file" onchange="setInitialValues(this.value)" accept=".svf" />
            </div>
        </div><!-- /.col -->
    </div>


    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.ColorBarName)
            </div>
        </div><!-- /.col -->

        <div class="col-md-3">
            <div class="form-group">
                @Html.TextBoxFor(m => m.ColorBarName, new { id = "colorBarName", style = "width: 300px;", required = "required", pattern = @"^([a-zA-Z0-9 _-]+)$", title = "Only use alphanumeric characters, space and [_, -]." })
            </div>
        </div>

        <div class="col-md-1">
            <div class="form-group">
                <input type="button" onclick="setControlValueToFilename('#colorBarName')" value="Use filename" />
            </div>
        </div>
    </div>
    <!-- /.col -->


    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.ColorBarDescription)
            </div>
        </div><!-- /.col -->

        <div class="col-md-3">
            <div class="form-group">
                @Html.TextBoxFor(m => m.ColorBarDescription, new { id = "colorBarDescription", style = "width: 300px;", pattern = @"^([a-zA-Z0-9 _-]+)$", title = "Only use alphanumeric characters, space and [_, -]." })
            </div>
        </div>

        <div class="col-md-1">
            <div class="form-group">
                <input type="button" onclick="setControlValueToFilename('#colorBarDescription')" value="Use filename" />
            </div>
        </div>
    </div>
    <!-- /.col -->


    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.PatchHeight)
            </div>
        </div><!-- /.col -->

        <div class="col-md-4">
            <div class="form-group">
                @Html.TextBoxFor(m => m.PatchHeight, new { style = "width: 80px;", type = "number", min = "0", step = "0.001" })
            </div>
        </div>
    </div>
    <!-- /.col -->


    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.EmailRecipients)
            </div>
        </div><!-- /.col -->

        <div class="col-md-3">
            <div class="form-group">
                @Html.TextBoxFor(m => m.EmailRecipients, new { style = "width: 300px;" })
            </div>
        </div>
    </div>
    <!-- /.col -->


    <div>
        <button type="submit" class="btn btn-primary">Convert!</button>
        @Html.ActionLink("All Processed Files", "Downloads", null, new { @class = "btn btn-default" })
    </div>
}


<script>
    function setcontrolToValue(control, value) {
        $(control).val(value);
    }

    function getFilenameFromPath(path) {
        var re = /([\w\d_-]*)\.?[^\\\/]*$/i;
        var filename = path.match(re)[1];
        return filename;
    }

    function setControlValueToFilename(control) {
        var files = $("#file").get(0).files;
        var selectedFile = files[0];
        var filename = getFilenameFromPath(selectedFile.name);
        setcontrolToValue(control, filename);
    }

    function setInitialValues(value) {
        var defaultColorBarName = @Html.Raw(Json.Encode(Model.DefaultColorBarName));
        var defaultColorBarDescr = @Html.Raw(Json.Encode(Model.DefaultColorBarDescription));

        if ($("#colorBarName").val() === defaultColorBarName) {
            setControlValueToFilename(setcontrolToValue('#colorBarName', getFilenameFromPath(value)));
        }

        if ($("#colorBarDescription").val() === defaultColorBarDescr) {
            setControlValueToFilename(setcontrolToValue('#colorBarDescription', getFilenameFromPath(value)));
        }
    }
</script>

svftocsv-converter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("HOME", "Index", "ConvertSvfToCsv", new {area = ""}, new {@class = "navbar-brand"})
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>